default:
  image: ruby:3.4
  before_script:
    - ruby -v
    - gem install bundler
    - bundle config set --local deployment true
    - bundle config set --local path 'vendor/ruby'
    - bundle install --with ci development test
  tags:
    - docker
    - shared


stages:
  - ci

cache:
  key:
    files:
      - Gemfile.lock
  paths:
    - vendor/ruby

brakeman:
  stage: ci
  script:
    - bundle exec brakeman -A -o brakeman-report.junit
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days
    reports:
      junit: './brakeman-report.junit'
  # rules:
  #  - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
  #    when: always
  #  - when: never

rubocop:
  stage: ci
  script:
    - bundle exec rubocop --format junit --out rubocop-report.xml
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days
    reports:
      junit: './rubocop-report.xml'

eslint:
  stage: ci
  image: node:22.17.1-alpine3.22
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  before_script:
    - yarn install
  script:
    - yarn run eslint app/javascript/**/*.js --ext .js
