image: ruby:3.4

stages:
  - brakeman
  - eslint

cache:
  key:
    files:
      - Gemfile.lock
  paths:
    - vendor/ruby

before_script: &before_script
  - ruby -v
  # - apt-get update -q && apt-get install nodejs -yqq
  - bundle config set --local deployment true
  - bundle config set --local path './vendor/ruby'
  - bundle install --with ci development test

brakeman:
  stage: brakeman
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days
    reports:
      junit: './report.junit'
  before_script: *before_script
  script:
    - bundle exec brakeman -A --color -o report.junit
  # rules:
  #  - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
  #    when: always
  #  - when: never

eslint:
  stage: eslint
  image: node:22.17.1-alpine3.22
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  before_script:
    - yarn install
  script:
    - yarn run eslint app/javascript/**/*.js --ext .js
  # rules:
  #  - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  #    when: always
  # - if: '$CI_PIPELINE_SOURCE == "push"'
  #   when: always
  # - when: never

