default:
  image: ruby:3.4
  before_script:
    - ruby -v
    - gem install bundler
    - bundle config set --local deployment true
    - bundle config set --local path 'vendor/ruby'
    - bundle install --with ci development test
  tags:
    - docker
    - shared

stages:
  - ci

cache:
  key:
    files:
      - Gemfile.lock
  paths:
    - vendor/ruby

brakeman:
  stage: ci
  script:
    - bundle exec brakeman -A -o brakeman-report.junit
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days
    reports:
      junit: './brakeman-report.junit'
  # rules:
  #  - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
  #    when: always
  #  - when: never

rubocop:
  stage: ci
  script:
    - bundle exec rubocop --format junit --out rubocop-report.xml
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days
    reports:
      junit: './rubocop-report.xml'

eslint:
  stage: ci
  image: node:22.17.1-alpine3.22
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  before_script:
    - yarn install
  script:
    - yarn run eslint app/javascript/**/*.js --ext .js

test:
  stage: ci
  image: docker:28.3.2-dind
  variables:
    ALLOWED_HOSTS: dmpopidor,localhost,0.0.0.0
  before_script:
    - docker compose build
    - docker compose run --rm dmpopidor sh -c 'ruby bin/docker postgres' --build-arg http_proxy=$http_proxy --build-arg https_proxy=$https_proxy
    - docker compose run --rm dmpopidor sh -c 'bin/rails db:environment:set RAILS_ENV=development; ruby bin/docker db:setup'
    - docker compose run --rm dmpopidor sh -c 'bundle exec rails db:setup RAILS_ENV=test'
    - docker compose run --rm dmpopidor sh -c 'bundle exec rails db:migrate RAILS_ENV=test'
    - docker compose up -d
  script:
    - echo "Run Rspec Unit and Functional Tests"
    - docker compose exec -it dmpopidor sh -c '
        bundle exec rspec \
          spec/models/ \
          spec/policies/ \
          spec/services/ \
          spec/helpers/ \
          spec/controllers/ \
          spec/presenters/ \
          spec/requests/ \
          spec/views \
          spec/mixins/
          --format RspecJunitFormatter \
          --out rspec-unit-functional-tests.xml
      '
    - echo "Run Integration Tests"
    - docker compose exec -it dmpopidor sh -c 'bundle exec rspec spec/features/ --format RspecJunitFormatter --out rspec-integration-tests.xml'
  after_script:
    - docker compose down
  artifacts:
    when: always
    expire_in: 30 days
    reports:
      junit:
        - rspec-unit-functional-tests.xml
        - rspec-integration-tests.xml
    paths:
      - rspec-unit-functional-tests.xml
      - rspec-integration-tests.xml
