.default: &default
  adapter: redis
  url: "redis://<%= ENV.fetch('REDIS_USERNAME', 'default') %>:<%= ENV.fetch('REDIS_PASSWORD', 'changeme') %>@<%= ENV.fetch('REDIS_HOST', 'localhost') %>:<%= ENV.fetch('REDIS_PORT', 6379) %>/1"

development:
  <<: *default
  channel_prefix: dmp_opidor_dev

test:
  adapter: async

production:
  <<: *default
  channel_prefix: dmp_opidor_production
