default: &default
  adapter: redis
  url: <%= Rails.configuration.x.dmpopidor.redis_url %>

development:
  <<: *default
  channel_prefix: dmp_opidor_dev

test:
  adapter: async

production:
  <<: *default
  channel_prefix: dmp_opidor_production
