selector: 'textarea.tinymce'
statusbar: false
menubar: false
toolbar: bold italic | bullist numlist | link | table
plugins:
  - table
  - autoresize
  - link
  - paste
  - advlist
advlist_bullet_styles: "circle,disc,square" #only disc bullets display on htmltoword
target_list: false
autoresize_min_height: 130
autoresize_bottom_margin: 10
extended_valid_elements: "iframe[tooltip] , a[href|target=_blank]"
extended_valid_elements: "a[href|target=_blank]"
paste_auto_cleanup_on_paste : true
paste_remove_styles: true
paste_retain_style_properties: "none"
paste_convert_middot_lists: true
paste_remove_styles_if_webkit: true
paste_remove_spans: true
paste_strip_class_attributes: "all"
table_default_attributes:
  border: 1